#version: '3.8'
#services:
#  client-backend:
#    image: client:0.0.1
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8181:8181"
#    environment:
#      - SERVER_PORT= 8181
#  prometheus:
#    image: prom/prometheus:v2.46.0
#    ports:
#      - 9090:9090
#    volumes:
#      - ./monitoring/prometheus/tmp:/prometheus
#      - ./monitoring/prometheus/config:/etc/prometheus
#    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
#
#  grafana:
#    image: grafana/grafana:10.0.3
#    ports:
#      - 3000:3000
#    volumes:
#      - ./monitoring/grafana/tmp:/var/lib/grafana
#      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
#
#  alertmanager:
#    image: prom/alertmanager:v0.25.0
#    ports:
#      - "9093:9093"
#    volumes:
#      - ./monitoring/alert-manager/tmp:/data
#      - ./monitoring/alert-manager/config:/config
#    command: --config.file=/config/alertmanager.yml --log.level=debug