groups:
  - name: Spring-boot
    rules:
      # Triggers a critical alert if a server is down for more than 1 minute.
      - alert: 5xx-over-2%
        expr: sum(rate(orders_5xx_total[1m]))/sum(rate({__name__=~"orders_*.xx_total"}[1m])) * 100 > 1
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: '{{ $labels }} {{ $value }} % breach'
