# Global configurations
global:
  scrape_interval: 15s
  evaluation_interval: 15s



# Scrape configurations
scrape_configs:
  - job_name: 'spring-boot-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8181']

rule_files:
  - 'alert-rules.yml'
alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ['host.docker.internal:9093']
